# Generated by Django 4.2.4 on 2023-11-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replyId',
            field=models.CharField(max_length=100),
        ),
    ]
